apiVersion: orchest.io/v1alpha1
kind: OrchestCluster
metadata:
  name: cluster-1
  namespace: orchest
spec:
  orchest:
    resources:
      builderCacheDirVolumeSize: 1Ti
      userDirvolumeSize: 1Ti


